# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Grover Lab
email: wgrover@engr.ucr.edu
description: > # this means to ignore newlines until "baseurl:"
  Grover Lab<br>
  Department of Bioengineering<br>
  University of California, Riverside<br>
  Riverside, CA 92521
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://groverlab.org" # the base hostname & protocol for your site
twitter_username: wgrover
github_username:  groverlab

# Build settings
markdown: kramdown




collections:
  people:
    output: true
  research:
    output: true
  education:
    output: true
    

